import type { ChatSuccessResponse } from '@/types/ai'

export type AiGenerateInput = {
  prompt: string
}

// Everything the model itself produces. `sources` is deliberately excluded —
// that field is populated by the retrieval layer, not generated by the model.
export type AiGenerateOutput = Omit<ChatSuccessResponse, 'sources'>

/**
 * Provider abstraction so callers (app/api/ai/chat/route.ts) never depend
 * on a specific vendor SDK directly. lib/ai/cloudflare.ts implements this
 * interface. No implementation, no network call, and no SDK import belongs
 * in this file.
 */
export interface AiProvider {
  generate(input: AiGenerateInput): Promise<AiGenerateOutput>
  embed(text: string): Promise<number[]>
}
