import type { ChatSuccessResponse } from '@/types/ai'
import { AiProviderError } from '@/lib/ai/generation-shared'
import { cloudflareProvider } from '@/lib/ai/cloudflare'
import { openaiProvider } from '@/lib/ai/openai'
import { geminiProvider } from '@/lib/ai/gemini'

export type AiGenerateInput = {
  prompt: string
}

// Everything the model itself produces. `sources` is deliberately excluded —
// that field is populated by the retrieval layer, not generated by the model.
// `routing` is deliberately excluded too: it carries real database ids
// (entityId/serviceId/complaintTypeId) and an officialUrl that must only ever
// be constructed server-side from RAG results / reference-table lookups —
// excluding it here means the model-provider return type can never contain
// an id field, structurally, not just by convention.
export type AiGenerateOutput = Omit<ChatSuccessResponse, 'sources' | 'routing'>

/**
 * Provider abstraction so callers (app/api/ai/chat/route.ts) never depend
 * on a specific vendor SDK directly. lib/ai/cloudflare.ts implements this
 * interface. No implementation, no network call, and no SDK import belongs
 * in this file.
 */
export interface AiProvider {
  generate(input: AiGenerateInput): Promise<AiGenerateOutput>
  embed(text: string): Promise<number[]>
}

/**
 * Generation-only subset of AiProvider — every generation provider
 * (Cloudflare, OpenAI, Gemini) implements this; only Cloudflare additionally
 * implements `embed` (embeddings stay on Cloudflare only, regardless of
 * which generation provider is active — no other provider needs to satisfy
 * the wider AiProvider shape).
 */
export type GenerationProvider = {
  generate(input: AiGenerateInput): Promise<AiGenerateOutput>
}

const SUPPORTED_AI_PROVIDERS = ['openai', 'cloudflare', 'gemini'] as const
type SupportedAiProvider = (typeof SUPPORTED_AI_PROVIDERS)[number]

/**
 * Server-side-only generation provider selection. Reads AI_PROVIDER once
 * per call — no caching of the *decision* itself, so a changed env var
 * always takes effect on the next request without a code change. Fails
 * safely (throws, never silently substitutes a different provider) on an
 * unset or unrecognized value — there is no default and no automatic
 * fallback between providers in either direction.
 */
export function getGenerationProvider(): GenerationProvider {
  const raw = process.env.AI_PROVIDER?.trim()

  if (!raw || !SUPPORTED_AI_PROVIDERS.includes(raw as SupportedAiProvider)) {
    throw new AiProviderError('AI_PROVIDER is not configured to a supported value.')
  }

  const provider = raw as SupportedAiProvider
  if (provider === 'openai') return openaiProvider
  if (provider === 'gemini') return geminiProvider
  return cloudflareProvider
}
