-- profiles: user can read/update their own row only.
-- No insert policy: rows are created exclusively by public.handle_new_user(),
-- which runs as a SECURITY DEFINER trigger on auth.users and bypasses RLS.
-- No delete policy: profile deletion is not a client-facing operation.
create policy "select own profile" on public.profiles
  for select to authenticated using (id = auth.uid());
create policy "update own profile" on public.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

-- conversations: direct user_id ownership, full CRUD.
create policy "select own conversations" on public.conversations
  for select to authenticated using (user_id = auth.uid());
create policy "insert own conversations" on public.conversations
  for insert to authenticated with check (user_id = auth.uid());
create policy "update own conversations" on public.conversations
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "delete own conversations" on public.conversations
  for delete to authenticated using (user_id = auth.uid());
-- Note: messages.conversation_id currently has no ON DELETE CASCADE in the
-- baseline schema, so deleting a conversation does not automatically remove
-- its messages today. Adding cascade behavior is a separate, explicit change
-- if the product flow ends up requiring it — not part of this migration.

-- messages: users read their own conversation's messages, and may only ever
-- insert role='user' messages into a conversation they own. Assistant/system
-- messages are written exclusively by trusted server-side code using the
-- service_role key, which bypasses RLS entirely — no policy is needed for that.
create policy "select own messages" on public.messages
  for select to authenticated using (
    exists (select 1 from public.conversations c where c.id = messages.conversation_id and c.user_id = auth.uid())
  );
create policy "insert own user messages" on public.messages
  for insert to authenticated with check (
    role = 'user'
    and exists (select 1 from public.conversations c where c.id = messages.conversation_id and c.user_id = auth.uid())
  );
-- No update or delete policy: messages are append-only from the client.

-- collected_information: read-only for the client. This table is populated
-- and maintained exclusively by trusted server-side AI logic (service_role).
create policy "select own collected_information" on public.collected_information
  for select to authenticated using (
    exists (select 1 from public.conversations c where c.id = collected_information.conversation_id and c.user_id = auth.uid())
  );
-- No insert/update/delete policy for the client.

-- complaints: read-only for the client in this migration. Complaint creation
-- and content updates go through trusted server-side actions (service_role)
-- so user_id can never be client-mutated; that stays out of RLS entirely by
-- not exposing a client insert/update path. If a self-serve insert/update or
-- delete is needed later, it must be added as its own reviewed migration with
-- explicit field-level checks (and user_id must never be updatable).
create policy "select own complaints" on public.complaints
  for select to authenticated using (user_id = auth.uid());

-- complaint_versions: read-only for the client. Versions are immutable,
-- system-generated history written exclusively by trusted server-side code.
create policy "select own complaint_versions" on public.complaint_versions
  for select to authenticated using (
    exists (select 1 from public.complaints x where x.id = complaint_versions.complaint_id and x.user_id = auth.uid())
  );
-- No insert/update/delete policy for the client.

-- retrieval_logs: read-only via parent conversation. System-generated by
-- service_role, which bypasses RLS — no write policy needed.
create policy "select own retrieval_logs" on public.retrieval_logs
  for select to authenticated using (
    exists (select 1 from public.conversations c where c.id = retrieval_logs.conversation_id and c.user_id = auth.uid())
  );

-- attachments: no policy in this file, or anywhere. Left completely untouched.
-- knowledge_documents: no policy in this file, or anywhere — inaccessible to
-- anon and authenticated by design.
